import Head from "next/head";
import parse from "html-react-parser";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Footer from "../components/Footer";
export default function Home() {
  const [data, setData] = useState([1, 2, 3, 4, 5, 6, 7, 8, 9]);

  const [result, setResult] = useState("");
  const [input, setInput] = useState("");

  const makeTable = (data) => {
    let result = ``;
    let longLength = data.length;
    for (let i = 0; i < longLength; i++) {
      result += `<tr>`;
      for (let j = 0; j <= longLength - 1; j++) {
        if (i === j) {
          result += `<td>${data[i]}</td>`;
        } else if (i + j === longLength - 1) {
          result += `<td>${data[longLength - 1 - i]}</td>`;
        } else {
          result += `<td></td>`;
        }
      }
    }
    result += `</tr>`;
    return result;
  };

  const makeInput = (e) => {
    e.preventDefault();
    setInput("");
    setData([]);
    if (input > 50) return alert("The number cannot be more then 50!");

    for (let i = 0; i < input; i++) {
      setData((prevState) => [...prevState, i + 1]);
    }
  };

  useEffect(() => {
    setResult(makeTable(data));
    // eslint-disable-next-line
  }, [data]);
  return (
    <div className={styles.container}>
      <Head>
        <title>X table algoritms - Made by Raihan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={makeInput}>
          <input
            type="number"
            onChange={(e) => setInput(e.target.value)}
            value={input}
            placeholder="masukan angka"
          />
          <br />
          <button onClick={makeInput}>Show Table</button>
        </form>
        <br />

        <table border="1">
          <tbody>{parse(`${result}`)}</tbody>
        </table>
      </main>
      <Footer />
    </div>
  );
}
